### ISSUE TITLE
Is there a way to filter data?

### ISSUE THREAD

**Issue by fabiocarneiro** [nilportugues/hal-json-transformer#5]
DateTime objects are returned in the api with it internal representation:

``` json
{
    "date": "2012-12-31 23:00:00.000000",
    "timezone_type": 3,
    "timezone": "UTC"
}
```

I would like to output date as a single ISO-8601 value (DateTime::ATOM). How would you recommend doing it using this library?

**Comment by nilportugues** [comment]
You should be converting data in the DTO before serializing it.

Separation of the internal and external representation is not meant to be solved by this library. It only saves you time writing transformer objects and serializing them to the standard.
